package us.proximal.spellwithme.controller.prime;

import android.content.Context;

import us.proximal.spellwithme.model.dao.WordsDAO;
import us.proximal.spellwithme.model.def.IWordsDAO;
import us.proximal.spellwithme.model.dto.WordDTO;

/**
 * Created by b on 11/26/14.
 */
public class PrimeWords {
    IWordsDAO dao;

    public void fillTheDatabaseWithWords(Context ctx){

        //This is important. The DAO needs the Context object for DB access
        dao = new WordsDAO(ctx);

        String [] dolch;

        dolch = makeDolch();

        for(int i=0;i<dolch.length;i++){
            WordDTO word = new WordDTO();
            word.setWord(dolch[i]);
            word.setDolch(true);
            word.setLength(dolch[i].length());
            dao.create(word);

        }

    }

    private String [] makeDolch(){
        String [] words = {
                "the",
                "to",
                "and",
                "he",
                "a",
                "I",
                "you",
                "it",
                "of",
                "in",
                "was",
                "said",
                "his",
                "that",
                "she",
                "for",
                "on",
                "they",
                "but",
                "had",
                "at",
                "him",
                "with",
                "up",
                "all",
                "look",
                "is",
                "her",
                "there",
                "some",
                "out",
                "as",
                "be",
                "have",
                "go",
                "we",
                "am",
                "then",
                "little",
                "down",
                "do",
                "can",
                "could",
                "when",
                "did",
                "what",
                "so",
                "see",
                "not",
                "were",
                "get",
                "them",
                "like",
                "one",
                "this",
                "my",
                "would",
                "me",
                "will",
                "yes",
                "big",
                "went",
                "are",
                "come",
                "if",
                "now",
                "long",
                "no",
                "came",
                "ask",
                "very",
                "an",
                "over",
                "your",
                "its",
                "ride",
                "into",
                "just",
                "blue",
                "red",
                "from",
                "good",
                "any",
                "about",
                "around",
                "want",
                "don’t",
                "how",
                "right",
                "put",
                "too",
                "got",
                "take",
                "where",
                "every",
                "pretty",
                "jump",
                "green",
                "four",
                "away",
                "old",
                "by",
                "their",
                "here",
                "saw",
                "call",
                "after",
                "well",
                "think",
                "ran",
                "let",
                "help",
                "make",
                "going",
                "sleep",
                "brown",
                "yellow",
                "five",
                "six",
                "walk",
                "two",
                "or",
                "before",
                "eat",
                "again",
                "play",
                "who",
                "been",
                "may",
                "stop",
                "off",
                "right",
                "never",
                "seven",
                "eight",
                "cold",
                "today",
                "fly",
                "myself",
                "round",
                "tell",
                "much",
                "keep",
                "give",
                "work",
                "first",
                "try",
                "new",
                "must",
                "start",
                "black",
                "white",
                "ten",
                "does",
                "bring",
                "goes",
                "write",
                "always",
                "drink",
                "once",
                "soon",
                "made",
                "run",
                "gave",
                "open",
                "has",
                "find",
                "only",
                "us",
                "three",
                "our",
                "better",
                "hold",
                "buy",
                "funny",
                "warm",
                "ate",
                "full",
                "those",
                "done",
                "use",
                "fast",
                "say",
                "light",
                "pick",
                "hurt",
                "pull",
                "cut",
                "kind",
                "both",
                "sit",
                "which",
                "fall",
                "carry",
                "small",
                "under",
                "read",
                "why",
                "own",
                "found",
                "wash",
                "show",
                "hot",
                "because",
                "far",
                "live",
                "draw",
                "clean",
                "grow",
                "best",
                "upon",
                "these",
                "sing",
                "together",
                "please",
                "thank",
                "wish",
                "many",
                "shall",
                "laugh"
        };

        return words;
    }
}
